### ISSUE TITLE
suggestion: comments system for Jekyll

### ISSUE THREAD

**Issue by raptazure** [CWKSC/Blog#3]
大佬更新好快啊...不过手动开 issue 感觉不够条理的样子，不知道[这个](https://aristath.github.io/blog/static-site-comments-using-github-issues-api)有用嘛，看起来效果还可以（没用过 Jekyll 人士路过 _(:_」∠)_

**Comment by CWKSC** [comment]
这个跟 utterances 差不多啦

ヾ( '' ´・ω・｀)ノ 是因为这样的：
发表评论的时候，用户要授权 OAuth 代表他们发帖 （要授权 (#`皿´)
或者用户直接去 GitHub Issues 上发表评论 （麻烦
感觉不太好

加上每次浏览都会请求一次 GitHub API
Github API 有速率限制，浏览数量多的时候就会炸掉
即便它每小时可以有 5000 个请求也是这样

另外是气氛和感觉，如果特意过来开 Issue 的话（或許）会变得比较严肃，比较会出现有深度的讨论

最后是，花在写 Blog 本身的时间比写文章多，我不要这样 (:」∠)_

**Comment by CWKSC** [comment]
（很认真地进行了解释）

**Comment by raptazure** [comment]
> （很认真地进行了解释）

唔嗯，确实（写 blog 比写文章时间长太真实了 (　ﾟдﾟ)
